app/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('messages/', views.room, name='room'),
    path('multichat/', views.multichat, name='multichat'),
]

tryDjango/urls.py
"""
Definition of urls for tryDjango.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from app import forms, views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('createevents/', views.createevents, name='createevents'),
    #path('contact/', views.contact, name='contact'),
    #path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('userinfo/', views.user_information, name='userinfo'),
    path('profile/', views.profile, name='profile'),
    path('clientlist/', views.clientlist, name='clientlist'),
    #path('addclients/', views.add_clients, name='addclients'),
    #path('removeclients/', views.remove_clients, name='removeclients'),
    path('clientsprofile/<int:client_id>/', views.client_profile, name='clientsprofile'),
    #path('clientsinformation/<int:client_id>/', views.client_information, name='clientsinformation'),
    #path('resourcedirectory/', views.resource_directory, name='resourcedirectory'),
    #path('directorylist/<int:pk>/', views.load_directory, name="directorylist"),
    #path('resourcelist/' , views.resourcelist, name= "resourcelist"),
    path('makeclientaccount/', views.make_client_account, name='makeclientaccount'),

    path('full_directory/', views.full_directory, name='fulldirectory'),
    path('sub_directory/<int:pk>/<int:option>', views.sub_directory, name='subdirectory'),

    path('org_directory/', views.org_directory, name='orgdirectory'),
    path('org_sub_directory/<int:pk>/', views.org_sub_directory, name='orgsubdirectory'),

    path('document_directory', views.document_directory, name='documentdirectory'),
    path('document_folder_directory/<int:pk>/<int:option>', views.document_directory_folder, name='document_folder_directory'),

    path('app/', include('app.urls')),
    path('reset_password/', PasswordResetView.as_view(template_name='app/reset_password.html'), name="reset_password"),
    path('reset_password_sent/', PasswordResetDoneView.as_view(template_name='app/reset_password_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='app/reset_password_confirm.html'), name="password_reset_confirm"), #encodes user ID in base 64, then uses the token to check if the password is valid, part of PasswordResetConfirmView documentation
    path('reset_password_complete/', PasswordResetCompleteView.as_view(template_name='app/reset_password_complete.html'), name="password_reset_complete"),
    path('upload/', views.BasicUploadView.as_view(), name='upload'),

    path('validateOrganization/', views.validate_org, name='validateOrganization'),
    path('validateAccount', views.validate_account, name='validateAccount'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.db.models.query import QuerySet
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm, ValidationError, modelformset_factory
from .models import *


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


"""Form for user creation"""
class User_Creation_Form(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': ''}), required=True)
    email = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': ''}), required=True)
    avatar = forms.ImageField(widget=forms.FileInput, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': ''}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': ''}), required=True)
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': ''}), required=True)
    middle_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': ''}), required=False)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': ''}), required=True)
    class Meta:
        model = Account
        fields = ("username", "email", "password1", "avatar", "first_name", "middle_name", "last_name",)

"""Form for user background information"""
class User_Bg(ModelForm):
    firstname = forms.CharField(label='First Name', required=False)
    lastname = forms.CharField(label='Last Name', required=False)
    middle_initial = forms.CharField(label='Middle Initial', required=False)
    phone_number = forms.CharField(label='Phone Number',)
    birthday = forms.DateField(label ='Birthdate (m/d/y)', widget=forms.DateInput(format='%m/%d/%Y'), input_formats=['%m/%d/%Y'])
    insurance_provider = forms.CharField(label='Insurance Provider', required=False)
    insurance_member_id = forms.CharField(label='Insurance Member ID', required=False)
    class Meta:
        model = BgInfo
        fields = '__all__'
        exclude = ('user',)

"""Form for user emergency contact information, not currently used in recent versions of the website, but it might be needed later"""
class User_EC(ModelForm):
    phone_number = forms.CharField(label='Phone Number',)
    primary_care_physician = forms.CharField(label='Primary Care Physician',)
    physician_phone = forms.CharField(label='Physician Phone',)
    class Meta:
        model = EcInfo
        fields = '__all__'
        exclude = ('background',)

"""Form for user demographic information"""
class User_Demo(ModelForm):
    apt_unit = forms.CharField(label='Apt Unit', required=False)
    ethnicity = forms.CharField(label='Ethnicity', required=False)
    race = forms.CharField(label='Race', required=False)
    class Meta:
        model = DemoInfo
        fields = '__all__'
        exclude = ('background',)

"""Form for user notes, aka the notes on a users profile (different than the ones seen on the dashboard)"""
class User_Notes(ModelForm):
    notes = forms.CharField(widget=forms.Textarea, label='',)
    class Meta:
        model = ClientNotes
        fields = '__all__'
        exclude = ('background',)

"""Form for adding clients to a client list (not currently used)"""
class Client_List(ModelForm):
    clients = forms.ModelMultipleChoiceField(queryset=Account.objects.filter(is_client=True, has_caseworker=False), widget=forms.CheckboxSelectMultiple)
    def __init__(self, request, *args, **kwargs):
        super(Client_List, self).__init__(*args, **kwargs)
        if request.user:
            current_clients = ClientList.objects.get(user=request.user)
            new_query = current_clients.clients.all()
            queryset = Account.objects.exclude(pk__in=new_query)
        self.fields['clients'].queryset = queryset

    class Meta:
        model = ClientList
        fields = '__all__'
        exclude = ('user',)

"""Form for removing clients from a client list (not currently used)"""
class Remove_Clients(ModelForm):
    clients = forms.ModelMultipleChoiceField(queryset=Account.objects.none(), widget=forms.CheckboxSelectMultiple)

    def __init__(self, request, *args, **kwargs):
        super(Remove_Clients, self).__init__(*args, **kwargs)
        if request.user:
            setlist = ClientList.objects.get(user=request.user)
            queryset = setlist.clients.all()
        else:
            queryset = ClientList.objects.none()
        self.fields['clients'].queryset = queryset

    class Meta:
        model = ClientList
        fields = '__all__'
        exclude = ('user',)

"""Form for adding a new organization"""
class Add_Organization(ModelForm):
    STATE_OPTIONS = (
            ('MD', 'MD'),
        )
    COUNTY_OPTIONS = (
            ('Worcester', 'Worcester'),
            ('Wicomico', 'Wicomico'),
            ('Somerset', 'Somerset'),
            ('Dorchester', 'Dorchester'),
        )

    org_name = forms.CharField(label = 'Full Organization Name', widget=forms.TextInput(attrs={'maxlength': '100'}), required = False)
    website = forms.CharField(label = 'Website URL', widget=forms.TextInput(attrs={'maxlength': '100'}), required = False)
    org_phone = forms.CharField(label = 'Primary Phone', widget=forms.TextInput(attrs={'placeholder': '(XXX)XXX-XXXX', 'maxlength': '13'}), required = False)
    org_email = forms.EmailField(label = 'Primary Email', widget=forms.EmailInput(attrs={'maxlength': '60'}),required = False)
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Add a short description of your organization here', 'maxlength': '500'}), required = False)
    eligibility = forms.ModelMultipleChoiceField(queryset=Eligibility.objects.all(), widget=forms.CheckboxSelectMultiple)

    street = forms.CharField(label = 'Street Address', widget=forms.TextInput(attrs={'maxlength': '100'}), required = False)
    apt_number = forms.CharField(label = 'Apt./Unit Number', widget=forms.TextInput(attrs={'maxlength': '10'}), required = False)
    city = forms.CharField(label = 'City', widget=forms.TextInput(attrs={'maxlength': '25'}), required = False)
    state = forms.CharField(label = 'State', widget=forms.Select(choices=STATE_OPTIONS), required = False)
    zipcode = forms.CharField(label = 'Zipcode', widget=forms.TextInput(attrs={'maxlength': '5'}), required = False)
    county = forms.CharField(label = 'County', widget=forms.Select(choices=COUNTY_OPTIONS), required = False)

    mail_street = forms.CharField(label = 'Street Address', widget=forms.TextInput(attrs={'maxlength': '100'}), required = False)
    mail_apt_number = forms.CharField(label = 'Apt./Unit Number', widget=forms.TextInput(attrs={'maxlength': '10'}), required = False)
    mail_city = forms.CharField(label = 'City', widget=forms.TextInput(attrs={'maxlength': '25'}), required = False)
    mail_state = forms.CharField(label = 'State', widget=forms.Select(choices=STATE_OPTIONS), required = False)
    mail_zipcode = forms.CharField(label = 'Zipcode', widget=forms.TextInput(attrs={'maxlength': '5'}), required = False)
    mail_county = forms.CharField(label = 'County', widget=forms.Select(choices=COUNTY_OPTIONS), required = False)

    contact_name = forms.CharField(label = 'Full Name', widget=forms.TextInput(attrs={'maxlength': '70'}), required = False)
    contact_phone = forms.CharField(label = 'Primary Phone', widget=forms.TextInput(attrs={'placeholder': '(XXX)XXX-XXXX', 'maxlength': '13'}), required = False)
    contact_title = forms.CharField(label = 'Title', widget=forms.TextInput(attrs={'maxlength': '50'}), required = False)
    contact_email = forms.CharField(label = 'Primary Email', widget=forms.EmailInput(attrs={'maxlength': '60'}), required = False)

    org_tags = forms.ModelMultipleChoiceField(queryset=PillTags.objects.all(), widget=forms.CheckboxSelectMultiple, required = False)
    org_image = forms.ImageField(widget=forms.FileInput, required=False)

    collaborators = forms.ModelMultipleChoiceField(queryset=Account.objects.filter(is_caseworker=True), widget=forms.CheckboxSelectMultiple, required = False)

    languages = forms.ModelMultipleChoiceField(queryset=Languages.objects.all(), widget=forms.CheckboxSelectMultiple, required = False)

    areas_served = forms.ModelMultipleChoiceField(queryset=Counties.objects.all(), widget=forms.CheckboxSelectMultiple, required = False)
    
    class Meta:
        model = Organizations
        fields = '__all__'
        exclude = ('lat', 'long',)

class filter(forms.Form):
    COUNTY_CHOICES = (
        ('Worcester', 'Worcester'),
        ('Wicomico', 'Wicomico'),
        ('Somerset', 'Somerset'),
        ('Dorchester', 'Dorchester'),
        )
    location = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=COUNTY_CHOICES)

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']

class GetBackgroundColorForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bgColor']

"""Form for adding an org to a sub directory"""
class AddOrgToSubDir(forms.Form):
    sub_dirs = forms.ModelMultipleChoiceField(queryset=SubDirectory.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={'class': 'customCBox'}))

"""Formset (allows for multiple of the same form) for adding tags"""
AddTagsFormset = modelformset_factory(

app/templates/not_used/add_individuals.html
{% extends 'app/layout.html' %}
{% block content %}
<head>
    <style>
        #id_first_name {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_last_name {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_phone_number {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_email {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_address {
            width: 286px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_city {
            width: 132px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_state {
            width: 70px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_zipcode {
            width: 70px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_description {
            width: 280px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_services_provided {
            width: 500px;
            height: 50px;
            font-family: Arial;
        }
        #id_skills_expertise {
            width: 500px;
            height: 50px;
            font-family: Arial;
        }
        div.serv {
            border-width: 2px;
            border-style: solid;
            width: 286px;
            height: 180px;
        }
    </style>
</head>
<h2>Add Individuals</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form1.first_name }}
    {{ form1.last_name }}
    <br />

    {{ form1.phone_number }}
    {{ form1.email }}
    <br />

    {{ form1.address }}
    <br />

    {{ form1.city }}
    {{ form1.state }}
    {{ form1.zipcode }}
    <br />

    {{ form1.description }}
    <br />

    <p>Services Provided</p>
    <a href="{% url 'addservices' %}">Add New Service Tag</a>
    <div class="serv">
    {{ form1.services_provided }}
    </div>

    <p>Skills & Expertise</p>
    <a href="{% url 'addskills' %}">Add New Skills & Expertise Tag</a>
    <div class="serv">
    {{ form1.skills_expertise }}
    </div>
    <br />

    <input type="submit" />
</form>
{% endblock %}

app/templates/not_used/add_organizations.html
{% extends 'app/layout.html' %}
{% block content %}
<head>
    <style>
        #id_org_name {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_phone_number {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_email {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_website {
            width: 138px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_address {
            width: 286px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_city {
            width: 132px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_state {
            width: 70px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_zipcode {
            width: 70px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_description {
            width: 280px;
            height: 30px;
            font-family: Arial;
            margin-bottom: 5px;
        }
        #id_services_provided {
            width: 500px;
            height: 50px;
            font-family: Arial;
        }
        div.serv {
            border-width: 2px;
            border-style: solid;
            width: 286px;
            height: 180px;
        }
    </style>
</head>
<h2>Add Organizations</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form1.org_name }}
    {{ form1.phone_number }}
    <br />

    {{ form1.email }}
    {{ form1.website }}
    <br />

    {{ form1.address }}
    <br />

    {{ form1.city }}
    {{ form1.state }}
    {{ form1.zipcode }}
    <br />

    {{ form1.description }}
    <br />

    <p>Services Provided</p>
    <a href="{% url 'addservices' %}">Add New Service Tag</a>
    <div class="serv">
    {{ form1.services_provided }}
    </div>
    <br />

    <input type="submit" />
</form>
{% endblock %}

app/templates/not_used/add_services.html
{% extends 'app/index.html' %}
{% load static %}
{% block content %}
<h2>Add Service Tags</h2>
<form method="post" class="signup_layout">
    {% csrf_token %}
    <p>{{ form1 }}</p>
    <br />
    <button type="submit">Submit</button>
</form>
{% endblock %}

app/templates/not_used/add_skills.html
{% extends 'app/index.html' %}
{% load static %}
{% block content %}
<h2>Add Skills Tags</h2>
<form method="post" class="signup_layout">
    {% csrf_token %}
    <p>{{ form1 }}</p>
    <br />
    <button type="submit">Submit</button>
</form>
{% endblock %}

app/templates/not_used/addclients.html
{% extends 'app/format.html' %}
{% block content %}
<head>
</head>
<h2>Add Clients</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form1 }}
    <input type="submit" />
</form>
{% endblock %}

app/templates/not_used/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/not_used/home.html
{% extends 'app/format.html' %}
<!-- working on creating a basic homepage by scartch -->
{% block content %}
    <h2>Homepage</h2>
    <p>Welcome to the UWLES Prototype!, {% if user.is.authenticated %}{{ user.username }}{% else %}visitor{% endif %}!</p>
    <p>
        <strong>Total users registered: </strong> {{ count }}
    </p>
{% endblock %}

app/templates/not_used/removeclients.html
{% extends 'app/format.html' %}
{% block content %}
<head>
</head>
<h2>Remove Clients</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form1 }}
    <input type="submit" />
</form>
{% endblock %}

app/templates/not_used/test4.html
<script>
    const csrf = document.getElementsByName('csrfmiddlewaretoken')
    const url = ""
    $(document).ready(function () {
        $('body').on('click', '.fas.fa-pencil-alt', function(){
            var noteid = $(this).val();
            const fd = new FormData()
            fd.append('csrfmiddlewaretoken', csrf[0].value)
            fd.append('noteid', noteid)
            $.ajax({
                type: 'POST',
                url: url,
                enctype: 'multipart/form-data',
                data: fd,
                success: function (response) {
                    $('.note-list-items[value='+ noteid +']').remove();
                },
                error: function (error) {
                    console.log(error)
                },
                cache: false,
                contentType: false,
                processData: false,
            })
    })
});
</script>

<ul class="note-list">
    {% note in notes %}
    <li class="notes-list-items" id="noteList" value="{{ note.id }}">
        <p class="note-date">{{ note.date }}</p>
        <button class="fas fa-pencil-alt" value="{{ note.id }}"></button>
        <button class="fas fa-times"></button>
        <p class="note-descript">{{ note.description }}</p>
    </li>
    {% endfor %}
</ul>